[
    {
        "_id": "Ktta",
        "name": "EC2",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "Host",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "kT8c",
                "type": "text",
                "name": "Internal IP",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "Cyy0",
                "type": "link",
                "name": "Cluster",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "Ktta",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": False,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "b8Jf",
                    "array_type": "single-select",
                    "array_data": {
                        "options": [
                            {
                                "name": "Dremio Cluster",
                                "id": "163812",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "Data Cluster",
                                "id": "402653",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "EX Cluster",
                                "id": "405969",
                                "color": "#FBD44A",
                                "textColor": "#FFFFFF",
                                "borderColor": "#E5C142",
                            },
                            {
                                "name": "Tableau Cluster",
                                "id": "206379",
                                "color": "#46A1FD",
                                "textColor": "#FFFFFF",
                                "borderColor": "#3C8FE4",
                            },
                            {
                                "name": "AWS Service",
                                "id": "466108",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                            {
                                "name": "Dev Cluster",
                                "id": "223729",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                        ]
                    },
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "Mi8a",
                "type": "link",
                "name": "InstanceType",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "Ktta",
                    "other_table_id": "D5Sb",
                    "is_internal_link": True,
                    "is_multiple": False,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "AJpF",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "ryJ0",
                "type": "link-formula",
                "name": "Core",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "formula": "lookup",
                    "result_type": "array",
                    "operated_columns": ["Mi8a"],
                    "conditions": [],
                    "link_column_key": "Mi8a",
                    "include_condition": False,
                    "condition_conjunction": "And",
                    "level1_linked_table_column_key": "ngp9",
                    "array_type": "number",
                    "array_data": {
                        "format": "number",
                        "decimal": "dot",
                        "enable_precision": True,
                        "precision": 0,
                        "thousands": "no",
                    },
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "cPHB",
                "type": "link-formula",
                "name": "Memory",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "formula": "lookup",
                    "result_type": "array",
                    "operated_columns": ["Mi8a"],
                    "conditions": [],
                    "link_column_key": "Mi8a",
                    "include_condition": False,
                    "condition_conjunction": "And",
                    "level1_linked_table_column_key": "RdMi",
                    "array_type": "number",
                    "array_data": {
                        "format": "number",
                        "decimal": "dot",
                        "enable_precision": True,
                        "precision": 0,
                        "thousands": "no",
                    },
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "an1e",
                "type": "link-formula",
                "name": "Annual_Price_OD_KRW",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "formula": "lookup",
                    "result_type": "array",
                    "operated_columns": ["Mi8a"],
                    "conditions": [],
                    "link_column_key": "Mi8a",
                    "include_condition": False,
                    "condition_conjunction": "And",
                    "level1_linked_table_column_key": "QqwQ",
                    "array_type": "number",
                    "array_data": {
                        "enable_precision": True,
                        "precision": 0,
                        "thousands": "comma",
                    },
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
                "colorbys": {
                    "type": "by_numeric_range",
                    "range_settings": {
                        "color_type": "color_gradation_9",
                        "is_custom_start_value": False,
                        "is_custom_end_value": False,
                        "start_value": "",
                        "end_value": "",
                    },
                },
            },
        ],
        "views": [
            {
                "_id": "ufUc",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [
                    {"column_key": "Cyy0", "sort_type": "up", "count_type": ""}
                ],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            },
            {
                "_id": "0000",
                "name": "Raw",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            },
        ],
        "summary_configs": {},
        "header_settings": {},
    },
    {
        "_id": "1Lm8",
        "name": "EFS",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "File System ID",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "05W9",
                "type": "text",
                "name": "Name",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "I0Ri",
                "type": "single-select",
                "name": "Mode",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "default_value": None,
                    "options": [
                        {
                            "name": "범용 / 탄력적 요금제",
                            "color": "#F4667C",
                            "textColor": "#FFFFFF",
                            "borderColor": "#DC556A",
                            "id": "540682",
                        },
                        {
                            "name": "범용 / 버스트",
                            "color": "#ADDF84",
                            "textColor": "#FFFFFF",
                            "borderColor": "#9CCF72",
                            "id": "815554",
                        },
                    ],
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "J5Q8",
                "type": "checkbox",
                "name": "For Managers",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {"enable_fill_default_value": False, "default_value": False},
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "rZVe",
                "type": "text",
                "name": "Description",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "n784",
                "type": "link",
                "name": "Target Cluster",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "1Lm8",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": False,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "PZgd",
                    "array_type": "single-select",
                    "array_data": {
                        "options": [
                            {
                                "name": "Dremio Cluster",
                                "id": "163812",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "Data Cluster",
                                "id": "402653",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "EX Cluster",
                                "id": "405969",
                                "color": "#FBD44A",
                                "textColor": "#FFFFFF",
                                "borderColor": "#E5C142",
                            },
                            {
                                "name": "Tableau Cluster",
                                "id": "206379",
                                "color": "#46A1FD",
                                "textColor": "#FFFFFF",
                                "borderColor": "#3C8FE4",
                            },
                            {
                                "name": "AWS Service",
                                "id": "466108",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                            {
                                "name": "Dev Cluster",
                                "id": "223729",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                        ]
                    },
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "0uBj",
                "type": "link",
                "name": "Accessible Clusters",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "1Lm8",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "e4S9",
                    "array_type": "single-select",
                    "array_data": {
                        "options": [
                            {
                                "name": "Dremio Cluster",
                                "id": "163812",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "Data Cluster",
                                "id": "402653",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "EX Cluster",
                                "id": "405969",
                                "color": "#FBD44A",
                                "textColor": "#FFFFFF",
                                "borderColor": "#E5C142",
                            },
                            {
                                "name": "Tableau Cluster",
                                "id": "206379",
                                "color": "#46A1FD",
                                "textColor": "#FFFFFF",
                                "borderColor": "#3C8FE4",
                            },
                            {
                                "name": "AWS Service",
                                "id": "466108",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                            {
                                "name": "Dev Cluster",
                                "id": "223729",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                        ]
                    },
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "mscj",
                "type": "text",
                "name": "DNS Name",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [
                    {"column_key": "n784", "sort_type": "up", "count_type": ""}
                ],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            }
        ],
        "summary_configs": {},
        "header_settings": {},
    },
    {
        "_id": "Gu3m",
        "name": "ECR",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "Name",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            }
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            }
        ],
        "summary_configs": {},
        "header_settings": {},
    },
    {
        "_id": "0000",
        "name": "Cluster",
        "columns": [
            {
                "key": "0000",
                "name": "Cluster",
                "type": "single-select",
                "width": 200,
                "editable": True,
                "resizable": True,
                "editor": {"key": None, "ref": None, "props": {}, "_owner": None},
                "formatter": {"key": None, "ref": None, "props": {}, "_owner": None},
                "data": {
                    "enable_fill_default_value": False,
                    "default_value": None,
                    "options": [
                        {
                            "name": "Dremio Cluster",
                            "id": "163812",
                            "color": "#F4667C",
                            "textColor": "#FFFFFF",
                            "borderColor": "#DC556A",
                        },
                        {
                            "name": "Data Cluster",
                            "id": "402653",
                            "color": "#F4667C",
                            "textColor": "#FFFFFF",
                            "borderColor": "#DC556A",
                        },
                        {
                            "name": "EX Cluster",
                            "id": "405969",
                            "color": "#FBD44A",
                            "textColor": "#FFFFFF",
                            "borderColor": "#E5C142",
                        },
                        {
                            "name": "Tableau Cluster",
                            "id": "206379",
                            "color": "#46A1FD",
                            "textColor": "#FFFFFF",
                            "borderColor": "#3C8FE4",
                        },
                        {
                            "name": "AWS Service",
                            "id": "466108",
                            "color": "#C2C2C2",
                            "textColor": "#FFFFFF",
                            "borderColor": "#ADADAD",
                        },
                        {
                            "name": "Dev Cluster",
                            "id": "223729",
                            "color": "#C2C2C2",
                            "textColor": "#FFFFFF",
                            "borderColor": "#ADADAD",
                        },
                    ],
                },
            },
            {
                "key": "9C4c",
                "type": "link",
                "name": "Platform",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "0000",
                    "other_table_id": "u73e",
                    "is_internal_link": True,
                    "is_multiple": False,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "3KJ5",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "bp5I",
                "type": "link",
                "name": "Service",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "AhpG",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "171m",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "s8k0",
                "type": "link",
                "name": "Host",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "Ktta",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "b8Jf",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "EK6y",
                "type": "link",
                "name": "EFS",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "1Lm8",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "e4S9",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "pin7",
                "type": "link",
                "name": "EFS 1",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "1Lm8",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "PZgd",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "is_locked": False,
                "rows": [],
                "formula_rows": {},
                "summaries": {},
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "hidden_columns": [],
                "groupbys": [],
                "groups": [],
                "colors": {},
                "column_colors": {},
                "link_rows": {},
            }
        ],
    },
    {
        "_id": "AhpG",
        "name": "Service",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "Service",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "bKVv",
                "type": "link",
                "name": "Cluster",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "AhpG",
                    "other_table_id": "0000",
                    "is_internal_link": True,
                    "is_multiple": False,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "171m",
                    "array_type": "single-select",
                    "array_data": {
                        "options": [
                            {
                                "name": "Dremio Cluster",
                                "id": "163812",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "Data Cluster",
                                "id": "402653",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "EX Cluster",
                                "id": "405969",
                                "color": "#FBD44A",
                                "textColor": "#FFFFFF",
                                "borderColor": "#E5C142",
                            },
                            {
                                "name": "Tableau Cluster",
                                "id": "206379",
                                "color": "#46A1FD",
                                "textColor": "#FFFFFF",
                                "borderColor": "#3C8FE4",
                            },
                            {
                                "name": "AWS Service",
                                "id": "466108",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                            {
                                "name": "Dev Cluster",
                                "id": "223729",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                        ]
                    },
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "rtFh",
                "type": "text",
                "name": "Description",
                "editable": True,
                "width": 201,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "g8oG",
                "type": "text",
                "name": "Annual_SW_Fee_KRW",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "FORO",
                "type": "text",
                "name": "Annual_HW_Fee_KRW",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "format_specification_value": None,
                    "default_value": "",
                    "format_check_type": "custom_format",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            }
        ],
        "summary_configs": {},
        "header_settings": {},
    },
    {
        "_id": "u73e",
        "name": "Platform",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "Platform",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "1F5x",
                "type": "link",
                "name": "Cluster",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "0000",
                    "other_table_id": "u73e",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "3KJ5",
                    "array_type": "single-select",
                    "array_data": {
                        "options": [
                            {
                                "name": "Dremio Cluster",
                                "id": "163812",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "Data Cluster",
                                "id": "402653",
                                "color": "#F4667C",
                                "textColor": "#FFFFFF",
                                "borderColor": "#DC556A",
                            },
                            {
                                "name": "EX Cluster",
                                "id": "405969",
                                "color": "#FBD44A",
                                "textColor": "#FFFFFF",
                                "borderColor": "#E5C142",
                            },
                            {
                                "name": "Tableau Cluster",
                                "id": "206379",
                                "color": "#46A1FD",
                                "textColor": "#FFFFFF",
                                "borderColor": "#3C8FE4",
                            },
                            {
                                "name": "AWS Service",
                                "id": "466108",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                            {
                                "name": "Dev Cluster",
                                "id": "223729",
                                "color": "#C2C2C2",
                                "textColor": "#FFFFFF",
                                "borderColor": "#ADADAD",
                            },
                        ]
                    },
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "GNwP",
                "type": "link-formula",
                "name": "Service",
                "editable": True,
                "width": 387,
                "resizable": True,
                "draggable": True,
                "data": {
                    "formula": "lookup",
                    "result_type": "array",
                    "operated_columns": ["1F5x"],
                    "link_column_key": "1F5x",
                    "level1_linked_table_column_key": "bp5I",
                    "level2_column_key_required": True,
                    "level2_linked_table_column_key": "0000",
                    "array_type": "text",
                    "array_data": None,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            }
        ],
        "summary_configs": {},
        "header_settings": {},
    },
    {
        "_id": "D5Sb",
        "name": "InstanceType",
        "is_header_locked": False,
        "columns": [
            {
                "key": "0000",
                "type": "text",
                "name": "InstanceType",
                "editable": True,
                "width": 123,
                "resizable": True,
                "draggable": True,
                "data": None,
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "ngp9",
                "type": "number",
                "name": "Core",
                "editable": True,
                "width": 95,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 0,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "no",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "3EfU",
                "type": "number",
                "name": "Price_OD_USD",
                "editable": True,
                "width": 153,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 2,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "no",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
                "editor": {"key": None, "ref": None, "props": {}, "_owner": None},
                "formatter": {"key": None, "ref": None, "props": {}, "_owner": None},
            },
            {
                "key": "RdMi",
                "type": "number",
                "name": "Memory_GB",
                "editable": True,
                "width": 146,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 0,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "no",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "Jd45",
                "type": "number",
                "name": "Annual_Price_RI1_USD",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 2,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "no",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
                "editor": {"key": None, "ref": None, "props": {}, "_owner": None},
                "formatter": {"key": None, "ref": None, "props": {}, "_owner": None},
            },
            {
                "key": "qWBk",
                "type": "number",
                "name": "Annual_Price_RI3_USD",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 2,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "no",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
                "editor": {"key": None, "ref": None, "props": {}, "_owner": None},
                "formatter": {"key": None, "ref": None, "props": {}, "_owner": None},
            },
            {
                "key": "QqwQ",
                "type": "formula",
                "name": "Annual_Price_OD_KRW",
                "editable": True,
                "width": 210,
                "resizable": True,
                "draggable": True,
                "data": {
                    "formula": "{Price_OD_USD} * 1320",
                    "operated_columns": ["3EfU"],
                    "result_type": "number",
                    "thousands": "comma",
                    "enable_precision": True,
                    "precision": 0,
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
            {
                "key": "lLFc",
                "type": "formula",
                "name": "Annual_Price_RI3_KRW",
                "editable": True,
                "width": 200,
                "resizable": True,
                "draggable": True,
                "data": {
                    "format": "number",
                    "precision": 0,
                    "enable_precision": True,
                    "enable_fill_default_value": False,
                    "enable_check_format": False,
                    "decimal": "dot",
                    "thousands": "comma",
                    "format_min_value": 0,
                    "format_max_value": 1000,
                    "formula": "{Annual_Price_RI3_USD}*1320",
                    "operated_columns": ["qWBk"],
                    "result_type": "number",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
                "editor": {"key": None, "ref": None, "props": {}, "_owner": None},
                "formatter": {"key": None, "ref": None, "props": {}, "_owner": None},
            },
            {
                "key": "nq0k",
                "type": "link",
                "name": "Host",
                "editable": True,
                "width": 599,
                "resizable": True,
                "draggable": True,
                "data": {
                    "display_column_key": "0000",
                    "table_id": "Ktta",
                    "other_table_id": "D5Sb",
                    "is_internal_link": True,
                    "is_multiple": True,
                    "is_row_from_view": False,
                    "other_view_id": "",
                    "link_id": "AJpF",
                    "array_type": "text",
                    "array_data": None,
                    "result_type": "array",
                },
                "permission_type": "",
                "permitted_users": [],
                "edit_metadata_permission_type": "",
                "edit_metadata_permitted_users": [],
                "description": None,
            },
        ],
        "views": [
            {
                "_id": "0000",
                "name": "Default View",
                "type": "table",
                "private_for": None,
                "is_locked": False,
                "row_height": "default",
                "filter_conjunction": "And",
                "filters": [],
                "sorts": [],
                "groupbys": [],
                "colorbys": {},
                "hidden_columns": [],
                "rows": [],
                "formula_rows": {},
                "link_rows": {},
                "summaries": {},
                "colors": {},
                "column_colors": {},
                "groups": [],
            }
        ],
        "summary_configs": {},
        "header_settings": {},
    },
]
